# SERVER
server.port=8080
spring.application.name=careconnect-service

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/careconnect_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Prakhar@411
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# JWT
jwt.secret=careconnect_jwt_secret_key_2026_must_be_at_least_256_bits_long_secure
jwt.expiration=86400000

# CONSUL (set enabled=true when Consul agent is running)
spring.cloud.consul.enabled=false
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${server.port}
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.prefer-ip-address=true

# SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method

# RESILIENCE4J CIRCUIT BREAKER
# Timeout: 3s, Failure threshold: 50%, Opens after 10 failures, Stays open: 60s
resilience4j.circuitbreaker.instances.careConnectCB.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.careConnectCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.careConnectCB.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.careConnectCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.careConnectCB.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.careConnectCB.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.careConnectCB.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.timelimiter.instances.careConnectCB.timeout-duration=3s

# ACTUATOR
management.endpoints.web.exposure.include=health,info,circuitbreakers,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

# JACKSON
spring.jackson.serialization.write-dates-as-timestamps=false

# LOGGING
logging.level.com.careconnect=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
